circle.yml

Build improvements

---

logging/event.go
logging/logging.go

Just copied across, no git history preservation.

Add service/common/logging as logging

---

middleware/logging.go

To help us figure out what's up with weaveworks/monitoring#82

Option for logging request headers

---

middleware/logging.go

Based on @tomwilkie's comment at https://github.com/weaveworks/scope/pull/2086#issuecomment-266491637

Log whether it's a websocket request

---

httpgrpc/httpgrpc.go

See https://github.com/grpc/grpc-go/issues/976 for discussion upstream.  Will need to be vendored into service before we enable grpc for Cortex.

Don't let grpc.Dial block the main authfe thread.

---

server/server.go

For use in the users service and the new thing.

Add cortex http/grpc server to common

---

middleware/logging.go

@tomwilkie, wdyt? as discussed the other day.

Instead of LogSuccess, use log levels for success vs failed requests

---

test/exec/exec.go

Needed by https://github.com/weaveworks/scope/pull/2335
I don't fully understand why it was introduced in the first place (there was no PR https://github.com/weaveworks/common/commit/201194aa4a9737826a1bdb9c3c2c38d244c0e5b3 ) but the Scope tests are happy without it.

test: Do not block when reading stderr pipe

---

middleware/path_rewrite.go

When a URL is parsed, the original url-encoded path goes in URL.RawPath,
and the decoded path in URL.Path.
URL's string method will use URL.RawPath, preserving the original encoding,
but only if URL.RawPath is a valid encoding of URL.Path.
If we modify URL.Path directly, this is no longer true, and URL then uses the un-escaped version of Path.
This has adverse effects since meaning can differ - for example, if the path contains an encoded / character
(ie. "%2F"), we want to preserve this as an encoded character, as otherwise it appears to be a path seperator.
"/foo%2Fbar" is not the same path as "/foo/bar".
We work around this by applying the regex to the escaped version instead, then reconstructing the unescaped version
from the new escaped version.
The new escaped version SHOULD be a …

middleware/path_rewrite: Don't inadvertently unescape url-encoded characters

---

logging/logging.go
user/logging.go

Related to https://github.com/weaveworks/service/issues/1233

Make it easy to get a logger with context information

---

http/client/client.go

A util to record HTTP request metrics

Add HTTP client request histogram function

---

user/id.go

Correct copy/paste error in context util

---

common-build/Dockerfile
http/client/client.go

Use interface for timing client requests

---

Gopkg.lock
instrument/instrument.go
instrument/instrument_test.go

Follow-up to #57 because that didn't really work. According to Damien doing it this way is only possible in Go1.9

Fix histogram instrumentation

---

middleware/response.go
middleware/response_test.go

Fix crash in badResponseLoggingHandler

---

middleware/logging.go

Set the status code on hijack to avoid spurious error reports

---

server/server.go

And remove hard-coded compression option added in #82

Let servers set any gRPC options they like

---

middleware/logging.go

Part of https://github.com/weaveworks/cortex/issues/810

Exempt 503 (Service Unavailable) from error logging

---

COPYING.LGPL-3

following https://github.com/weaveworks/build-tools/pull/138

license: document that assert.sh is under LGPLv3

---

tracing/tracing.go

Expose jaeger metrics

---

middleware/logging.go
server/server_test.go

When logging an http request, e.g. on 500 error, put all the headers and response on one line.
This makes it far easier to scan and search logs.
Also strip cookies and csrf tokens on security grounds.
Before:
```
WARN: 2018/07/30 15:16:41.157804 POST /api/users/gcp/subscribe (500) 393.651867ms
WARN: 2018/07/30 15:16:41.157846 Is websocket request: false
POST /api/users/gcp/subscribe HTTP/1.1
Host: users.default.svc.cluster.local.
Connection: close
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: close
Content-Length: 34
Content-Type: application/x-www-form-urlencoded
Cookie: redacted7F05FA21071BD7424A|22709e2b85d7cbe8a4810; redacted3979587.1526746; redactedredactedredactedredactedredactedredactedy9ABCJ2NHZ_6s=
Origin: https://cloud.weave.works …
```

Improve logging of http errors

---

Gopkg.lock
httpgrpc/server/server.go
server/server.go

This is just a change of location - the code is the same.

go-grpc-middleware has moved

---

server/server.go

Expose RegisterInstrumentation setting

---

server/server_test.go

(with exception of http port, which we override for the convenience of people running the tests as an ordinary user who can't bind to port 80)

Extend tests to check server works with flag defaults

---

server/certs/genCerts.sh

Follow up from https://github.com/weaveworks/common/pull/185#discussion_r412778848 
Signed-off-by: Annanay <annanayagarwal@gmail.com>

[nit] Move shebang to first line, add commit hash to link

---

tracing/tracing.go

I've found myself wanting to set some options (tracer tags, etc), and figured this should work fine without breaking existing code.
Signed-off-by: Dave Henderson <dhenderson@gmail.com>

tracing: add options to NewFromEnv

---

server/server.go

This is used by Grafana Agent.

server: Support custom prometheus.Registerer,Gatherer

---

server/server.go

Server TCP related metrics `tcp_connections` and `tcp_connections_limit` are currently always registered with the default prometheus registry: https://github.com/prometheus/client_golang/blob/main/prometheus/registry.go#L57
As a result, it can cause an attempt to register duplicate metrics collector failing with a panic. This can happen for instance in a testing scenario.
This PR updates these metrics to use the configured Registry, if any, otherwise, the default Prometheus Registry.
`log` and `gatherer` initializations were also moved for consistency.

Bugfix server tcp metrics to use the configured registry or the default Prometheus registry
