middleware/instrument.go
Part of a fix for weaveworks/monitoring#82 -- we aren't detecting websocket handshakes correctly
=> Correct websocket detection

middleware/redirect.go
As we're getting rid of the nginx frontend, the authfe need to redirect from scope.weave.works to cloud.w.w and http://cloud.w.w to https.
=> Add redirect middleware

middleware/grpc_auth.go
See https://github.com/weaveworks/cortex/issues/240
=> Prevent concurrent map writes by merging grpc metadata.

exec/exec.go, test/exec/exec.go
Needed for https://github.com/weaveworks/scope/pull/2277
=> Add SetEnv() to Cmd mocking interface

middleware/instrument.go
When using the `tmpl` variable to create a route match, the error should be `nil` i.e. no error.
Fixes #25
=> invert logic in getRouteName

user/http.go, user/id.go
There are plans to rename "orgID" in weave cloud to "instanceID" and "userID" in cortex to "principalID".
This change makes it clearer which ID these functions are extracting in the meantime.
=> Update HTTPRequest extract functions to make it clear which ID they are extracting

middleware/http_auth.go, user/grpc.go, user/http.go, user/id.go
We have been using the term `userID` to refer to instances (which we call `orgID` elsewhere in our codebase, e.g. headers). We wish to use both `orgID` and `userID` (the individual) in a new service.
This change renames `userID` to `orgID` and creates a new context key for actual `userID`'s (the individuals).
I have proxied the old functions to the `orgID` ones to not break dependant code.
=> Use orgID and userID for the user context

fs/fs.go, fs/fs_test.go, fs/readdircount_linux_amd64.go, fs/readdircount_unsupported.go, test/fs/fs.go
ReadDirNames is expensive and better avoided when we don't care about
the names.
-----
This is for https://github.com/weaveworks/scope/pull/2456
TODO:
=> fs: add ReadDirCount

server/server.go
=> Fix typo in comment

http/http.go
This was a mistake in #43, without this the client package isn't available through dep
=> Add http package so that http/client is available

server/server.go
So Server can be used for internet-facing services.
Default of false preserves existing behaviour.
=> Add option to not register instrumentation routes.

logging/logging.go
Motivating example is to not excessively log the same http 4xx code over and over from the same ip,
as this doesn't add info and bloats our log volume.
This requires some abuse of logrus to work, but we do this via a formatter which can either emit the original message,
or the empty string to log no message (this is harmless). Later, a seperate goroutine will emit a new log
that logs the original log and how many times it occurred.
We always log the first time we see a given message, then start a timer. If we see the message again at least once in that
time frame, we log at the end of the time frame how many times.
Note this means we can say "repeated once", which is a little confusing but preferable to displaying the original message
unchanged but time delayed, which can be very …
=> logging: Add ability to deduplicate log messages

middleware/grpc_logging.go
And also emit the method and duration as fields so they can be parsed out
The code to generate the log entry is adapted from https://github.com/weaveworks/cortex/pull/452, which does the same thing for the Prometheus log interface.
=> Include the orgID when logging gRPC calls

user/logging.go
I was wondering why the billing API never logged anything helpful...
=> Log the userID & orgID if we have it, not if we don't

aws/config.go, aws/config_test.go
Code was extracted from weaveworks/cortex
This is so we can re-use the fix from https://github.com/weaveworks/cortex/pull/537 in Scope and elsewhere
Note it does not include the line that disables retries; that is particular to Cortex and has to be added back there.
=> Add ConfigFromURL helper function

middleware/logging.go, middleware/response.go
Part of https://github.com/weaveworks/service/issues/1233 
This is kind of a significant change, as it intercepts *all* incoming requests. I haven't done much in the way of testing.
Also changes the logging order slightly. Previously, when `LogRequestHeaders` was on, we would log headers then request/response summary (method, status, etc). Now, we log method, status, etc. _then_ headers.
=> Log request headers, response headers and some body as warning on 500s

user/grpc.go
https://github.com/grpc/grpc-go/pull/1157 changed the APIs for getting
metadata from contexts and making contexts from metadata.
This PR updates common to rely on the new library.
Means that anyone who vendors common will need a recent grpc-go too.
=> Use new gRPC APIs

Gopkg.lock, backoff/backoff.go, backoff/backoff_test.go, httpgrpc/httpgrpc.go, logging/logging.go, middleware/grpc_logging.go, middleware/logging.go, middleware/path_rewrite.go, sanitize/sanitize.go, server/server.go, user/logging.go
[Promrus](https://github.com/marccarre/promrus/) is a Logrus hook to expose the number of log messages as [Prometheus](https://prometheus.io/) metrics:
```
log_messages{level="debug"}
log_messages{level="info"}
log_messages{level="warning"}
log_messages{level="error"}
```
Added dependency using:
```
$ dep ensure github.com/weaveworks/promrus@v1.0.0 && dep ensure && dep prune
```
Fixed casing in `logrus` imports, causing the following issue:
```
middleware/grpc_logging.go:10:2: case-insensitive import collision:
"github.com/weaveworks/common/vendor/github.com/Sirupsen/logrus" and
"github.com/weaveworks/common/vendor/github.com/sirupsen/logrus"
```
by:
- changing `import` statements from `Sirupsen/logrus` to `sirupsen/logrus`, as per [the official …
=> Add Prometheus metrics for number of log messages

user/http.go
To avoid copying the names into other modules.
=> Header names are public members

middleware/instrument.go, middleware/logging.go, middleware/response.go
Fixes #68 
Reverts #69 since it was [misguided](https://github.com/weaveworks/common/issues/68#issuecomment-336499041)
I moved `interceptor` to beside where it is used because the location in `logging.go` confused me,
and applied the advice from `interceptor` to `badResponseLoggingWriter` - 
> `WriteHeader` may not be called on success, so initialize `statusCode` with the status you want to report on success, i.e. `http.StatusOK`.
And I've even tried running it.
=> Stop reporting zero status

http/client/client.go, instrument/instrument.go
New method is named `client.TimeRequest()`. This avoids
recreation of the collector on every request.
Also adds `instrument.HistogramCollectorFromOpts()` and
makes the interface `instrument.Collector` public.
=> Add timed client request taking a collector

http/client/client.go, http/client/client_test.go
This helps in chaining clients doing requests. Such as
client.NewTimedClient(http.DefaultClient, someCollector}
=> Add `client.TimedClient` implementing `Requester`

instrument/instrument.go
This is handy when debugging.  ~I limit the length arbitrarily just in case someone has dumped their life-story into the error string.~
=> Add error message to OpenTracing span

instrument/instrument.go, server/server.go
Previously we would clamp at 10 seconds, giving a misleading impression for things that can take a lot longer to respond.
=> Extend histogram buckets for a server up to 100 seconds

server/server.go
A feature for larger payloads.  Whether it is used or not is controlled at the client side.
=> Let servers support gzipped gRPC

middleware/logging.go
These are not usually caused by the problems with the request, and just result in spammy logs during local development.
=> Don't log request body and headers for 502 errors

Gopkg.lock, Gopkg.toml
By default, go dep will take the latest stable version released. For client_golang this means it will lock the 0.8.0 version from 2016-08-17. It seems a sub-optimal default and was causing our golang services to be missing interesting metrics and bug fixes.
Also filed: https://github.com/prometheus/client_golang/issues/375
=> Update prom client go

tracing/tracing.go
This commit allows Cortex systems to specify, per-service, how trace sampling should be handled in the Jaeger client. Given that `jaeger.SamplerTypeConst` yields an all-or-nothing approach to sampling, Production deployments of Cortex are effectively blocked from enabling Jaeger traces. The load generated on Jaeger Collector (and its data store) is immense with a sampling probability of 1, even for moderate-sized deployments.
There's a partner PR (https://github.com/weaveworks/cortex/pull/703) to enable Cortex components to take advantage of this, defaulting to `jaeger.SamplerTypeRateLimiting` with a param of `10.0` to yield ~10 traces per second being shipped when `JAEGER_AGENT_HOST` is set at runtime. This is easily swapped for an alternate sampling strategy, however.
=> Add args to tracing.New to allow configurable trace sampling

Gopkg.lock, middleware/grpc_logging.go, server/server.go
#85 added across-the-board logging of gRPC body contents on failed requests, which blows up the Ingester logs on a failed push.
In my perusal so far, ingester push failures currently log either:
* Nothing at all about the relevant series
* All the pertinent details such as metric name, label values, latest value, incoming value, etc.
This change should simply retain the old logging behavior for ingester push failures, while still enhancing logging of other RPC failures across the system.
@bboreham, I think this may unblock https://github.com/weaveworks/cortex/pull/709 (once vendored in of course). What are your thoughts?
=> Don't log full request body on failed /cortex.Ingester/Push calls

server/server.go
=> Remove Loki initialisation from server.go.

Gopkg.lock, Gopkg.toml, circle.yml, middleware/grpc_auth.go, middleware/grpc_instrumentation.go, middleware/grpc_logging.go, server/server.go
Adds a series of gRPC _stream_ middleware for logging, user header propagation and tracing.  This is laying groundwork for using gRPC streaming between ingesters and queriers in Cortex.
=> Add gRPC streaming middleware.

tracing/tracing.go
Reporting trace spans for a request is a separate task from choosing which requests should be traced.
Fixes #101
=> When trace reporting is enabled, don't enable trace sampling unless asked

server/server.go
gRPC behaviour should be the same as HTTP: `Run()` exits when a signal is received, and `Stop()` stops the handling of requests.
See https://github.com/weaveworks/cortex/issues/882
=> Don't shutdown the gRPC server the minute a signal is received.

instrument/instrument.go
This should make it easier to do things like filter on an instance.
=> Add user and org ID to tracing span if known

httpgrpc/server/server.go, httpgrpc/server/server_test.go
=> Propagate tracing context over httpgrpc

middleware/instrument.go
Random people on the Internet can send in arbitrary paths, so collapse them all into "other" when reporting metrics.
Fixes #106
=> Don't use full URL as metric label on unmatched path

Makefile
This was missed in the earlier change (#98) to use the image from build-tools.
=> Set $SRC_PATH as required by the build container

server/server.go
Primary motivation is to allow a standard Go profiling request to complete, for which I only need the write timeout, but I raised the other 5-second timeouts too since it isn't that unusual to have operations or data uploads take longer.
=> Raise default server timeouts from 5s to 30s

aws/config.go, aws/config_test.go
See https://github.com/weaveworks/cortex/pull/898
=> Allow the AWS backend to get credentials from its environment.

test/diff.go
Fixes #80.  Finally got sick of overriding it locally.
This new setting will make it print the difference between `String()` output only.  This is more usable for developers in 99% of cases where the difference can be seen.
=> Default diff-printer to hide details

server/server.go
This allows users to inject HTTP requests and have the logged, instrumented and traced correctly.
See https://github.com/weaveworks/cortex/issues/949
=> Expose the HTTP server from the server struct.

middleware/http_tracing.go, server/server.go
Pulls https://github.com/weaveworks/scope/pull/3325 into common, and factors out server initialisation code
=> Add HTTP tracing middleware

middleware/http_tracing.go, middleware/logging.go, server/server.go
```
level=debug ts=2018-08-28T15:57:09.13499093Z caller=gokit.go:29 traceID=75e33027dba459a3 msg="GET /api/prom/api/v1/query?query=prometheus_test_exporter_now_seconds%7Bjob%3D%22dev%2Ftest-exporter%22%7D%5B59m%5D&time=2018-08-21T02%3A03%3A08.019055392Z (200) 67.490589ms"
```
This'll help with debugging query latencies and other things quite easy.
=> Print traceID with request

logging/logging.go, logging/logrus.go
This PR sets the global logging instance when calling `logging.Setup(level)`.
Previously, only the standard logrus logger was set up and if anyone used
the new funcs such as `logging.Info()` it was discarded.
=>  Also set global logging when initializing logrus

httpgrpc/server/server.go, httpgrpc/server/server_test.go
This was introduced in #105, and breaks query-frontend -> querier trace propagation in cortex - specifically, this inserts a span between the client and server span, causing them not to be associated with each other in the jaeger UI correctly.  @leth is there any background on why this was nessecary?
The way I see it, when using httpgrpc you should propagate your context using grpc (using https://github.com/grpc-ecosystem/grpc-opentracing/tree/master/go/otgrpc middleware on the grpc clients and servers).  And when using http, you should propagate your context using the nethttp library (https://github.com/opentracing-contrib/go-stdlib).  But you shouldn't mix them.  
You can simulate the effect of this PR by wrapping the handler passed to httpgrpc in the nethttp middleware if you need to.
=> Don't trace http requests when using httpgrpc.

Gopkg.lock, logging/logging.go, logging/logrus.go
This changes the way logrous outputs log messages in case there is no
TTY attached.
Changes from
ERRO: 2018/08/23 20:28:10.075952 Sample log message extra=foo
to
time="2018-08-23T20:28:10Z" level=info msg="Sample log message" extra="foo"
which follows the `logfmt` key-value format by also providing `time`,
`level`, and `msg` in adition to the extra fields.
The PR removes the custom `textFormatter` to have the default
`logrus.TextFormatter` in place which takes care of detecting whether a
terminal is attached or not and switches between text and logfmt output
automatically.
It appears the custom formatter was to prevent differences in rendering
depending on color/non-color output which I don't necessarily see as an
issue.
=> Print logrus output in logfmt format

Gopkg.lock, Gopkg.toml, httpgrpc/README.md, httpgrpc/httpgrpc.go
It seems to be necessary to decode errors as `github.com/gogo/protobuf/types.Any` rather than `github.com/golang/protobuf/ptypes/any`, following #117, otherwise we get failures to decode errors.
It is possible this relates more to versions of the libs than the specific code - there are a number of issues in the gogo repos around `Any`, and I had to add some overrides in a downstream repo to get the latest:
```
[[override]]
name = "github.com/gogo/googleapis"
version = "v1.1.0"
[[override]]
name = "github.com/gogo/status"
version = "v1.0.3"
```
=>  Update more golang/protobuf to gogo/protobuf

httpgrpc/server/server.go, httpgrpc/server/server_test.go
Causes problems if you try and connect from one namespace to another.
=> Fix dropped namespace in url parsing

Gopkg.lock, Gopkg.toml, httpgrpc/server/server.go, httpgrpc/server/server_test.go
=> Update to latest kuberesolver

server/server.go
Motivation here is making Cortex "single-binary" easier to use.
=> Log which ports the server is listening on.

logging/level.go, server/server.go
This is so we can load flags from a YAML file in Cortex.
=> Allow server.Config to be unmarshaled from YAML.

instrument/instrument.go
Cancellations are always caused by something else, so having them show up as errors in the tracing UI is distracting.
=> Dont flag context.Canceled as an error in tracing

server/server.go, server/server_test.go
NB This use the gRPC defaults as the flag defaults.
=> Allow overriding max message sizes and concurrent streams in the gRPC server.

middleware/grpc_logging.go
Context cancellations are controlled by clients and logging this message can
cause more more confusion as mentioned here:
https://github.com/cortexproject/cortex/issues/1279
Signed-off-by: Neeraj Poddar <neeraj@aspenmesh.io>
=> Skip logging context cancelled warning msgs

server/server.go
Previously calling `Subrouter()` would overwrite the instrumentation handlers and they'd be ignored when PathPrefix was specified. This meant one could never get back metrics or debug endpoints.
I verified metrics and api endpoints respond with this change locally, but writing a test didn't work as creating a new `Server` (via `New(..)`) mutates global state and prometheus panics on duplicate metric registrations. We could pass in a prometheus registry, but that breaks the public constructor. 
```go
func TestInstrumentationPathPrefix(t *testing.T) {
var cfg Config
cfg.PathPrefix = "/loki/"
cfg.HTTPListenPort = 10101
cfg.RegisterInstrumentation = true
server, err := New(cfg)
require.NoError(t, err)
go server.Run()
defer server.Shutdown()
resp, err := …
```
=> server: use -server.path-prefix for metrics and debug endpoints

logging/level.go, logging/level_test.go
Needed to Cortex can print its own config.
=> Allow log levels to be marshalled to YAML.  Test it works.

Gopkg.lock, server/server.go
With this, `prometheus.Handler()` became `promhttp.Handler()`.
=> Update prometheus/client_golang and prometheus/procfs

aws/config.go
If the scheme was set to https, respect https otherwise default to http as always.
=> use https if provided as scheme

aws/config.go
Allow region to be read from environment variable.
For using custom s3 endpoint, some providers expects valid endpoint with valid `region`. This change should allow to use region from environment variable. If not defined it will fallback to `dummy`
Fixes #165
=> Allow region to be read from environment variable

server/server.go, server/server_test.go
=> Allow user to specify HTTP and gRPC bind addresses (not just ports.) (Rebase of #153)

Gopkg.lock, server/server.go
We ran into a situation where it would be good to limit the total number of connections. This PR adds an optional configuration to limit the number of simultaneous connections to the server. The package used to enable this is the [netutil LimitListener](https://godoc.org/golang.org/x/net/netutil#LimitListener).
Signed-off-by: Jacob Lisi <jacob.t.lisi@gmail.com>
=> Limit the number of connections to server

signals/signals.go
If we exit the handler loop, e.g. after receiving SIGTERM, then we don't want Go to attempt further delivery of signals.
=> Tell Go runtime we have stopped listening to signals

httpgrpc/server/server.go, httpgrpc/server/server_test.go
According to https://github.com/grpc/grpc-go/blob/v1.19.0/clientconn.go#L125 the URLs to pass to gRPC should have three slashes. 
Empirically this works better in my environment.
=> Fix kuberesolver URLs to have three slashes

go.mod, middleware/http_tracing.go
Update the OpenTracing library to a version which supports Websockets, and remove the workaround for when it didn't.
=> Trace Websockets requests

server/server.go
We are running into issues with with load balancing the distributors in cortex. We are using DNS resolution with the httpgrpc client. However, the default resolution frequency of the client is 30 minutes. Since we don't want to roll a custom resolver, the other recommended approach is to set the `max_connection_age` of the grpc server (https://github.com/grpc/grpc/issues/12295).
This PR entails the following:
* Flags to set the GRPC Server Keepalive configs that will be passed as options upon creation
* Flags default to the default values of the `grpc-go` package
* Because we don't roll the config struct itself, there are no `yaml` tags, so it won't be able to be read from a config file
Signed-off-by: Jacob Lisi <jacob.t.lisi@gmail.com>
=> add flags to configure keep alive configs

tracing/tracing.go
Fixes #181 
Also, we should add a watcher so that when jaeger is up, tracing can be initialized. Should we leave this logic to client or can we implement it here?
=> BREAKING CHANGE: Return error in configuring jaeger

go.mod, go.sum
Updates the vendored `prometheus/node_exporter` dependency which sets min TLS version to 1.2, as 1.0 and 1.1 are considered insecure.
Signed-off-by: Annanay <annanayagarwal@gmail.com>
=> Update node_exporter version

server/certs/genCerts.sh, server/server.go, server/server_test.go
In Cortex, we currently have extra logic [(as explained here)](https://github.com/cortexproject/cortex/pull/2542#discussion_r417884587) to handle the fact that `server.Server` type handles SIGINT/SIGTERM signals, that should trigger shutdown of entire server.
This PR adds ability to disable signal handling by Server. This will make it possible to handle signal by Cortex `Run` method instead, and to trigger shutdown of all services (incl. `Server`) cleanly, without doing [special hacks](https://github.com/cortexproject/cortex/blob/master/pkg/cortex/modules.go#L529-L534) for "Server" service. 
Option to disable signal handling is deliberately "negative" ("disable", not "enable"), to keep existing code working as before.
=> Added option to disable signal handling by Server.

middleware/logging.go, middleware/logging_test.go, middleware/response.go
See discussion here: https://github.com/cortexproject/cortex/pull/2483#discussion_r411273751
Requires projects to use Go 1.13 and above
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>
=> Log errors when write fails, not 200; requires Go 1.13

logging/format.go, logging/gokit.go, logging/logrus.go, server/server.go
Add option to specify log output format to be json
not sure if unknown formats should be rejected? I don't see the option of returning an error
Related grafana/loki#1885
=> add log format option

aws/config.go, aws/config_test.go
Starting from an issue opened in Cortex https://github.com/cortexproject/cortex/issues/3034, I've realised an edge case in `aws.ConfigFromURL()`. If the URL is in the format `scheme://@host/path`, the static credentials are configured in the S3 config but with an empty ID / secret, because no user/pass is specified in the URL before the `@`.
In this PR I'm proposing a fix for that.
=> Fixed aws.ConfigFromURL() when URL contains @ but no user/pass

server/server.go, server/server_test.go
Add an option to change the Router and an option to not add the default middleware.
Signed-off-by: Michel Hollands <michel.hollands@grafana.com>
=> Make HTTP middleware optional

server/server.go
We'd like to modify gRPC keepalive policies on the server, but these options are currently not exposed.
This PR changes that.
Note that default values are consistent with gRPC server options.
=> Expose gRPC keepalive enforcement policy options.

tracing/tracing.go
=> tracing: Allow specifying JAEGER_ENDPOINT instead of sampling server or local agent port

httpgrpc/server/server.go
This way we can easily get direct access to the underlaying `bytes.Buffer`. This means we don't need to copy the data anymore.
Signed-off-by: Cyril Tovena <cyril.tovena@gmail.com>
=> Replace `ioutil.NopCloser` with a custom one.

httpgrpc/server/server.go
http.NewRequest can't set it while using a `io.NopCloser`.
Signed-off-by: Cyril Tovena <cyril.tovena@gmail.com>
=> Set the content-length of httpgrpc request.

middleware/instrument.go, server/server_test.go
When router can't find the route but it has the `NotFoundHandler` set, the `RouteMatch` doesn't have the `Route` set but it has `MatchErr` set to `ErrNotFound`.
Added a check for `RouteMatch.Route` to be not nil before accessing it, and added a special `"notfound"` route name to be used when `NotFoundHandler` is used.
Signed-off-by: Oleg Zaytsev <mail@olegzaytsev.com>
=> Fix panic in server instrumentation matching NotFoundHandler

middleware/counting_listener.go, middleware/counting_listener_test.go, server/server.go, server/server_test.go
Counts the number of accepted connections and the number of closed
connections, by intercepting the listener for each port (http/grpc).
Signed-off-by: Steve Simpson <steve.simpson@grafana.com>
=> Add metric "tcp_connections" for number of TCP connections to server.

instrument/instrument.go, instrument/instrument_test.go, middleware/grpc_instrumentation.go, middleware/http_tracing.go, middleware/instrument.go, middleware/logging.go, server/server.go, tracing/tracing.go
Whenever a duration is observed and we have a trace ID, store it as a Prometheus exemplar.
Follow-up to #202 
This is a breaking change to the `Collector` interface and the location of `ExtractTraceID`; apologies if you are impacted.
I felt the `middleware` package should not be a dependency of `instrument`, and the assumption that traces are Jaeger is better placed in the `tracing` package where we set up Jaeger.
Note also that the gRPC code path creates a trace before recording the histogram time, instead of the other way round.
I don't expect this will have any measurable effect.
=> Add exemplars to 'instrument' package and gRPC interceptors

server/server.go
There are a lot of tests which create a `server.Config{}` and don't populate the network fields; allow this by setting `DefaultNetwork` if blank.
Also pick up a bugfix where `HTTPListenNetwork` was used for gRPC.
=> Allow blank network in server.New

server/server.go
So that we can pass the trace ID as an exemplar.
This was done for unary RPCs in #220 but I missed the stream case.
=> gRPC stream middleware: move metrics after tracing

middleware/http_tracing.go
Often it can be useful to understand, which kind of client is behaving in a certain way.
That's why this PR adds a tag to the HTTP trace middleware to annotate the span with the user-agent header of the request.
=> Add a tag with the user-agent to traces

middleware/logging.go, middleware/logging_test.go, server/server.go
Adds an optional flag to log requests at the info level, still defaulting to logging requests at the debug level.
=> Add flag to log requests at info level

instrument/instrument.go
Exemplars provide information about traces, and traces usually reference to the user that served the request, however, searching the user in the trace is usually a tedious task, and it would be nice to be able to overwiew whether the slow requests (exemplars) from your panel corresponds to the same user.
We could even consider adding exemplars from non-traced requests that have a user ID? This would provide (poor) insights about the request patterns even for the users who run the server without tracing set up.
=> Add user and org labels to observed exemplars

middleware/grpc_logging.go, middleware/grpc_logging_test.go, server/server.go
@pracucci asked me to modify https://github.com/weaveworks/common/pull/241 to make the debug log configurable instead of removing it
=> Make debug logs on successful requests from GRPCServerLog optional

server/server.go, server/server_test.go
I would like to remove advanced TLS config parameters stemming from github.com/prometheus/exporter-toolkit/web, that were introduced in commit [953ac9fb41437fee0bffcb364333ba624a35e043](https://github.com/weaveworks/common/commit/953ac9fb41437fee0bffcb364333ba624a35e043):
* `cipher_suites`
* `curve_preferences`
* `min_version`
* `max_version`
* `prefer_server_cipher_suites`
The motivation for removing these advanced parameters is that users would most likely not want to change them, and they add corresponding configuration parameters to the Grafana Mimir project, that we don't want. We also think they're not interesting to the Grafana Tempo and Loki projects.
=> server: Removing advanced TLS config parameters - BREAKING CHANGE

instrument/instrument.go
Reverts weaveworks/common#237
[Prometheus will panic](https://github.com/prometheus/client_golang/blob/3d482bb7cfa10c0cd0d6d3f80cf77b8ce24435bd/prometheus/value.go#L202-L237) if the total length of all labels and their values exceeds 64 runes.
This means that we can't have a user input on the exemplars labels.
=> Revert "Add user and org labels to observed exemplars"

server/server.go
The main rationale is for "choosing" random unbinded port for testing.
It's one of the Go's idiom to pass port number `0` to enforce Go's net's package to bind to some random port that is free.
example:
```
package main
import (
"log"
"net"
"net/http"
"time"
"google.golang.org/grpc"
)
func main() {
httpListener, err := net.Listen("tcp", "0.0.0.0:0")
if err != nil {
panic(err)
}
grpcListener, err := net.Listen("tcp", "0.0.0.0:0")
if err != nil {
panic(err)
}
h := http.Server{}
go func() {
log.Println("http serving at", httpListener.Addr())
h.Serve(httpListener)
}()
g := grpc.Server{}
go func() {
log.Println("grpc serving at", grpcListener.Addr())
g.Serve(grpcListener)
}()
time.Sleep(20 * time.Second)
}
```
And that will bind random "unassigned" port.
```
2022/08/08 16:51:49 grpc serving at …
```
=> server: Expose `http` and `grpc` listen addresses.

go.mod, middleware/grpc_logging_test.go
This removes a test dependency on `github.com/go-kit/kit/log`, which was otherwise replaced with `github.com/go-kit/log` back in #226
The `go.mod` diff was done by running `go mod tidy` - no changes except for whitespace there
Signed-off-by: Dave Henderson <dhenderson@gmail.com>
=> Fix incorrect import of obsolete github.com/go-kit/kit/log package

.circleci/config.yml, Makefile, httpgrpc/httpgrpc.proto
There is no `weaveworks/build-golang` image newer than Go 1.14, and we don't really need one.
For CI, switch to using CircleCI's image, and for local builds assume the user has Go installed.
Also switch to `golangci-lint`, although I suppressed any pre-existing issues.  Can fix them in a different PR.
The one thing which is tricky to set up locally is protobuf generation, which is not used in CI.
The fact that the three `.pb.go` files in this repo were generated using two different proto commands suggests it was never done consistently.
To avoid leaving protos broken, I have used a 3rd-party image `namely/protoc:1.22_1`, which generates identical
output for two of the protos in this repo.
The third one, httpgrpc, I have not managed to match exactly, but the result is very close.
I have …
=> Update CI build to Go 1.17; drop BUILD_IN_CONTAINER

httpgrpc/server/server.go
On projects consuming this module as a library, gRPC might be set at
newer versions where the deprecated #WithBalancerName has been removed
already. Given that the version used by this module already offers a
forward-compatible method, this commit uses that instead of the
deprecated #WithBalancerName.
This is a simplified version of #240, without touching the gRPC versions.
Fixes #239
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
=> httpgrpc/server: Update NewClient to not use WithBalancerName

middleware/logging.go, middleware/response.go, middleware/response_test.go
This PR adds `Flush()` to the `middleware.badResponseLoggingWriter`, making it implement `http.Flusher`.
I think, ideally, none of this middleware should interfere with what the ultimate HTTP handlers want to try to do. Making a best-effort attempt at `Flush()` seems like the friendliest behavior for middleware; if it can flush, great, otherwise nothing happens.
Additionally, I think this best-effort type behavior plays nicely with [this disclaimer](https://pkg.go.dev/net/http#Flusher) about `http.Flusher`:
> Note that even for ResponseWriters that support Flush, if the client is connected through an HTTP proxy, the buffered data may not reach the client until the response completes.
=> Add badResponseLoggingWriter.Flush

middleware/logging.go, middleware/logging_test.go, server/server.go
Previously the log middleware would exclude printing only the headers "Cookie", "Authorization" and "X-Csrf-Token". I believe the users of this library may want to ommit more headers than those.
To do so I've changed how the middleware is initialize to optionally add more headers to the list.
Also I've added a unit test to make sure the behavior works as expected.
Also I've added an optional configuration parameter to the server to set LogRequestHeaders from there. This parameter was already an option in the log middleware but was not exposed in the server.
Signed-off-by: Jesus Vazquez <jesus.vazquez@grafana.com>
=> Log middleware now accepts a list of headers to exclude

go.mod, go.sum, server/server.go
This is an opt-in via setting Config.MetricsNativeHistogramFactor so that nobody will expose native histograms by accident. Even if native histograms are enabled, the conventional histograms are still maintained and presented as before to scrapers incapabale of scraping native histograms.
Native histograms were tested previously in the sparse-histograms branch without any problems. This commit obsoletes the sparse-histograms branch.
The histograms request_message_bytes and response_message_bytes are left as conventional histograms for now. Maybe they would work well as native histograms with a bucket factor of 2, as high resolution is not the aim here. But we can decide about that once we have gathered more experience with the native histograms for request_duration_seconds.
The settings …
=> Enable Prometheus native histograms for request_duration_seconds

go.mod, go.sum, middleware/errorhandler.go, middleware/response.go, middleware/response_test.go
This PR adds `Unwrap` method to all implementations of `http.ResponseWriter`.
New https://pkg.go.dev/net/http#ResponseController introduced in Go 1.20 uses `Unwrap` method to get access to original `http.ResponseWriter` or underlying connection.
My use case: I'd like to use `http.ResponseController` to set longer timeouts on HTTP endpoints for uploading big files, overriding global `-server.http-write-timeout` and `-server.http-read-timeout`. 
This PR also updates httpsnoop library to version 1.0.3, which supports `Unwrap` method as well (since 1.0.2) (https://github.com/felixge/httpsnoop/issues/8).
(To make weaveworks/common fully compatible with new `http.ResponseController`, `opentracing-contrib/go-stdlib` library needs an update too, after …
=> Add Unwrap method to http.ResponseWriter implementations.

server/server.go
Automation on user side (Grafana Mimir) cannot distinguish between faulty or intentionally empty description at this moment. Suggest adding some meta information if we want to have such "hidden" flags. But people dumping request header should know what they are doing so I think it's ok to not hide these.
=> Add description to command line flags

go.mod, go.sum, server/server.go
This PR uses https://github.com/soheilhy/cmux to provide the ability to route both HTTP and GRPC over the HTTP port with all of the GRPC server settings.
Currently it routes http1 to the http server and all http2 to the GRPC server.
=> Add support to route both GRPC and HTTP over the HTTP server

server/metrics.go, server/server.go, server/server_test.go
As discussed in https://github.com/weaveworks/common/issues/285 - this PR adds ability to manually register metrics, for example, when users restart the Server, but want to reuse existing and already registered metrics.
It does so by introducing a new, alternative constructor function for the server so a user can pick the preferred implementation:
```
// New makes a new Server. It will panic if the metrics cannot be registered.
func New(cfg Config) (*Server, error) {
metrics := NewServerMetrics(cfg)
metrics.MustRegister(cfg.registererOrDefault())
return newServer(cfg, metrics)
}
// NewWithMetrics makes a new Server using the provided Metrics. It will not attempt to register the metrics,
// the user is responsible for doing so.
func NewWithMetrics(cfg Config, metrics *Metrics) (*Server, …
```
=> Allow users to manually register metrics

grpc/cancel.go
This improves behaviour when one error wraps another.
=> grpc: use errors.Is to check if error is Canceled
